# Generated by Django 5.1.6 on 2025-03-24 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from celery import shared_task
from django.utils.timezone import now
from django.core.mail import send_mail
from .models import Task


class Migration(migrations.Migration):

    dependencies = [
        ('KiddieRemind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]




@shared_task
def send_task_reminders():
    tasks = Task.objects.filter(due_date__lte=now(), is_completed=False)
    for task in tasks:
        send_mail(
            subject="Task Reminder: " + task.title,
            message=f"Reminder! Your task '{task.title}' is due soon.",
            from_email="no-reply@kiddieremind.com",
            recipient_list=[task.created_by.email],
        )
