# Generated by Django 5.1.6 on 2025-03-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KiddieRemind', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('homework', 'Homework'), ('chores', 'Chores'), ('activities', 'Activities'), ('reminders', 'Reminders'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
